  link:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: ${LINK_DOMAIN}
      EXPOSE: ${EXPOSE}
      GATEWAY_CLIENT_WG_PRIVKEY: ${WG_PRIVKEY}
      GATEWAY_LINK_WG_PUBKEY: ${GATEWAY_LINK_WG_PUBKEY}
      GATEWAY_ENDPOINT: ${GATEWAY_ENDPOINT}
      # Remove following to disable basic authentication
      BASIC_AUTH: admin:admin
      # Remove following line to get certs from Let's Encrypt
      TLS_INTERNAL: true
      # CADDY_TLS_PROXY: true
      # CADDY_TLS_INSECURE: true
      # FORWARD_ONLY: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
# #     uncomment to preserve tls certs
#     volumes:
#       - caddy_data:/data
# # uncomment to preserve tls certs
# volumes:
#   caddy_data:
